FastcampusMini/mini-project

mini-project/src/main/java/com/fast/miniproject/product/entity/Basket.java
mini-project/src/main/java/com/fast/miniproject/product/entity/Product.java
mini-project/src/main/java/com/fast/miniproject/product/entity/Wishlist.java

- Change 1
- Description
- Change 2
- Description
- Change 3

Entity 리팩토링

---

mini-project/src/main/java/com/fast/miniproject/auth/controller/AuthController.java
mini-project/src/main/java/com/fast/miniproject/auth/controller/PageController.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/SignupReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/entity/Token.java
mini-project/src/main/java/com/fast/miniproject/auth/jwt/JwtFilter.java
mini-project/src/main/java/com/fast/miniproject/auth/jwt/JwtProperties.java
mini-project/src/main/java/com/fast/miniproject/auth/jwt/JwtProvider.java
mini-project/src/main/java/com/fast/miniproject/auth/repository/UserRepository.java
mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/UserServiceImpl.java
mini-project/src/main/java/com/fast/miniproject/global/config/SecurityConfig.java
mini-project/src/main/resources/templates/index.html

전반적인 리팩토링과, 테스트코드, 패스워드 암호화 추가. 
- 패스워드 암호화 기능 추가
- 토큰 체크 기능 강화
- DB 저장하기전 체크 추가
- 간단 테스트페이지 추가
우리팀원분들

회원가입, 로그인 , 테스트페이지, 추가하였습니다.

---

mini-project/src/main/java/com/fast/miniproject/search/Controller/SearchProductController.java
mini-project/src/main/java/com/fast/miniproject/search/Service/SearchProductService.java
mini-project/src/main/java/com/fast/miniproject/search/repository/SearchProductRepository.java

SearchProduct Repository, Service, Controller 생성
- Change 1
- https://github.com/FastcampusMini/mini-project/issues/7 (아래 세개 전부 생성하면서 상품 이름 기반 검색 기능도 구현)
- dbfe1955 : SearchProductRepository 생성 및 기능 구현
- f6889723 : SearchProductService 생성 및 기능 구현
- 18e0524e : SearchProductConroller  생성 및 기능 구현

Feature/search 상품 이름 기반 검색 기능 구현

---

mini-project/.gitignore
mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
mini-project/src/main/java/com/fast/miniproject/product/dto/ProductDetailDTO.java
mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

Feat product detail

---

mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

금융상품 구현
- Change 1
- controller 구현 
- Change 2
- repository 구현
- Change 3
- service 구현
코드리뷰 해주세요

feat: 금융상품 추천 기능 구현

---

mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
mini-project/src/main/java/com/fast/miniproject/product/dto/OrderDetail.java
mini-project/src/main/java/com/fast/miniproject/product/dto/ProductIdList.java
mini-project/src/main/java/com/fast/miniproject/product/entity/Order.java
mini-project/src/main/java/com/fast/miniproject/product/entity/OrderProductBridge.java
mini-project/src/main/java/com/fast/miniproject/product/entity/PurchasedProduct.java
mini-project/src/main/java/com/fast/miniproject/product/repository/OrderProductBridgeRepository.java
mini-project/src/main/java/com/fast/miniproject/product/repository/OrderRepository.java
mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
mini-project/src/main/java/com/fast/miniproject/product/repository/PurchaseProductRepository.java
mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

상품 구매 로직 구현
#6 
- ProductService
- ProductController

상품 구매 기능 구현

---

mini-project/src/main/java/com/fast/miniproject/auth/controller/AuthController.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/PatchUserReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/PatchUserResDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/entity/User.java
mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/UserServiceImpl.java
mini-project/src/main/java/com/fast/miniproject/auth/service/UserService.java

회원정보 수정까지만 구현 완료.
resolve #12 
우리팀원들

회원정보 수정 구현 완료

---

mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
mini-project/src/main/java/com/fast/miniproject/product/dto/OrderDetail.java
mini-project/src/main/java/com/fast/miniproject/product/entity/Order.java
mini-project/src/main/java/com/fast/miniproject/product/entity/OrderProductBridge.java
mini-project/src/main/java/com/fast/miniproject/product/entity/PurchasedProduct.java
mini-project/src/main/java/com/fast/miniproject/product/repository/OrderProductBridgeRepository.java
mini-project/src/main/java/com/fast/miniproject/product/repository/ProductRepository.java
mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

상품 구매 기록 조히
- OrderEntity
- fetchType Eager
- OrderProductBridge
- fetchType Eager
- PurchasedProduct
- fetchType Eager

상품 구매 기록 조회

---

mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

예외처리 구현
- Change 1
- 추천상품  예외처리
- Change 2
- 금융상품 전체 보여주는 거 예외처리
- Change 3
코드 리뷰 부탁드립니다

feat: 예외처리 구현

---

mini-project/src/main/java/com/fast/miniproject/product/dto/OrderDetail.java
mini-project/src/main/java/com/fast/miniproject/product/dto/OrderListResp.java
mini-project/src/main/java/com/fast/miniproject/product/entity/OrderProductBridge.java
mini-project/src/main/java/com/fast/miniproject/product/entity/Orders.java
mini-project/src/main/java/com/fast/miniproject/product/repository/OrderProductBridgeRepository.java
mini-project/src/main/java/com/fast/miniproject/product/repository/OrderRepository.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

for loop 삭제 후 single query 사용으로 변경.
OrderEntity 이름 변경 Order -> Orders
order_date -> purchaseDate
tableName 또는 columnName 변경이 아님!
#31 
- Order 
- Order -> Orders
- order_date -> purchaseDate

for loop 삭제 및 OrderEntity 주요 변경 사항

---

mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

구매 상품 없는경우 예외처리

---

mini-project/src/main/java/com/fast/miniproject/global/response/PageResponseDTO.java
mini-project/src/main/java/com/fast/miniproject/search/controller/SearchProductController.java
mini-project/src/main/java/com/fast/miniproject/search/repository/SearchProductRepository.java
mini-project/src/main/java/com/fast/miniproject/search/service/SearchProductService.java

SearchProduct Repository, Service, Controller 생성
- Change 1
- https://github.com/FastcampusMini/mini-project/issues/25
- a01bc06d : 앞으로의 모든 api에서 페이징 처리 후  반환할때 필요한 Global PageResponseDTO생성 (최종 반환형은 ResponseDTO<PageResponseDTO>)
- d280c14f, 392e76d8, db457584 : Search 기능에서 반환을 페이징 처리하고 반환하기 위한 Controller, Service, Repository 수정

Feature/search Search 패키지에서의 페이징 처리 구현

---

mini-project/build.gradle
mini-project/src/main/java/com/fast/miniproject/auth/controller/AuthController.java
mini-project/src/main/java/com/fast/miniproject/global/config/SecurityConfig.java
mini-project/src/main/java/com/fast/miniproject/global/config/SwaggerConfig.java

스웨거를 추가하였습니다.
각자 본인이 작업한 컨트롤러에 정보 입력 부탁해요.
application.properties  에 아래 내용 추가해야 합니다. 
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
- [Swagger Link](http://localhost:8080/swagger-ui/index.html)

스웨거 추가하였습니다.

---

mini-project/src/main/java/com/fast/miniproject/auth/controller/AuthController.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/DeleteUserReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/PatchUserReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/UserServiceImpl.java
mini-project/src/main/java/com/fast/miniproject/auth/service/UserService.java
mini-project/src/main/java/com/fast/miniproject/global/config/SecurityConfig.java
mini-project/src/main/java/com/fast/miniproject/global/config/SwaggerConfig.java

이제 스웨거로 json 테스트가 가능합니다.
로그인 테스트후에 생성되는 토큰을 복사하여 우측 상단에 자물쇠 Authorize 클릭하여 붙여넣기 해주시면
요청시 헤더에 토큰이 같이 들어가서 해당 토큰 사용자가 요청한것처럼 테스트가 가능합니다.
스웨거 안되시는분은 application.properties에 코드 추가해야 합니다.
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
resolve #47

이제 스웨거로 json 테스트가 가능합니다.

---

mini-project/src/main/java/com/fast/miniproject/auth/controller/AuthController.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/DeleteUserReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/LoginReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/PatchUserReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/PatchUserResDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/dto/SignupReqDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/TokenServiceImpl.java

프론트 앤드 auth 요청사항 추가

---

mini-project/src/main/java/com/fast/miniproject/product/controller/BasketController.java
mini-project/src/main/java/com/fast/miniproject/product/controller/ProductController.java
mini-project/src/main/java/com/fast/miniproject/product/controller/WishlistController.java

API rename

---

mini-project/src/main/java/com/fast/miniproject/InitDb.java

init db 샘플 상품 리스트 로고 랑 상호 동일하게 수정

프론트 앤드 요청사항

---

mini-project/src/main/java/com/fast/miniproject/product/controller/BasketController.java
mini-project/src/main/java/com/fast/miniproject/product/controller/WishlistController.java
mini-project/src/main/java/com/fast/miniproject/product/service/WishlistService.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/WishlistServiceImpl.java

경로 통일을 위한 수정, 사용하지 않는 코드 삭제
- Change 1
-  복수형으로 경로 통일
- Change 2
- 사용하지 않는 코드 삭제

URL 경로 수정, 불필요한 코드 삭제

---

mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

주문 관련 메소드 이름 및 접근제한자 변경

---

mini-project/src/main/java/com/fast/miniproject/product/dto/BasketResponseDTO.java
mini-project/src/main/java/com/fast/miniproject/product/dto/WishlistResponseDTO.java

장바구니, 위시리스트 ResponseDTO에 detail, rate 추가
- Change 1
- 장바구니 ResponseDTO에 detail, rate 추가
- Change 2
- 위시리스트 ResponseDTO에 detail, rate 추가
- Change 3

feat: 프론트 요청 사항 수정

---

mini-project/src/main/java/com/fast/miniproject/auth/dto/PatchUserResDTO.java
mini-project/src/main/java/com/fast/miniproject/auth/entity/RefreshToken.java
mini-project/src/main/java/com/fast/miniproject/auth/service/Impl/UserServiceImpl.java
mini-project/src/main/java/com/fast/miniproject/global/config/SecurityConfig.java
mini-project/src/main/java/com/fast/miniproject/product/service/ProductService.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

사용자 대출 가능 금액 반환
PUBLIC URLS 수정

Feat 사용자 대출 가능 금액 반환

---

mini-project/build.gradle
mini-project/src/main/java/com/fast/miniproject/search/controller/SearchProductController.java
mini-project/src/main/java/com/fast/miniproject/search/repository/SearchProductRepository.java
mini-project/src/main/java/com/fast/miniproject/search/repository/SearchProductRepositoryCustom.java
mini-project/src/main/java/com/fast/miniproject/search/repository/SearchProductRepositoryImpl.java
mini-project/src/main/java/com/fast/miniproject/search/service/SearchProductService.java

Querydsl 5.0.0 버전 사용가능하게 설정 & 검색기능 추가
- Change 1
- https://github.com/FastcampusMini/mini-project/issues/67
- c8e0d2f9, 2d49f552, 7ae92838 : 위 이슈와 관련된 Repository 관련 변경 사항
- d78544c6 : 위 이슈와 관련된 Service 관련 변경 사항
- b789b18c : 위 이슈와 관련된 Controller 관련 변경 사항
- Change 2
- https://github.com/FastcampusMini/mini-project/issues/70
- 38a97cb2 : Querydsl 관련 설정 추가

Feature/search 검색 기능 추가 및 Querydsl 설정

---

mini-project/src/main/java/com/fast/miniproject/global/config/SwaggerConfig.java
mini-project/src/main/java/com/fast/miniproject/global/config/Workaround.java

- Workaround.java
- SwaggerConfig.java

fix : swagger 테스트 IP 변경

---

mini-project/src/main/java/com/fast/miniproject/global/config/SwaggerConfig.java
mini-project/src/main/java/com/fast/miniproject/global/config/Workaround.java

Reverts FastcampusMini/mini-project#73

Revert "fix : swagger 테스트 IP 변경"

---

mini-project/src/main/java/com/fast/miniproject/auth/exception/UserException.java
mini-project/src/main/java/com/fast/miniproject/auth/exception/UserExceptionType.java
mini-project/src/main/java/com/fast/miniproject/search/controller/SearchProductController.java
mini-project/src/main/java/com/fast/miniproject/search/repository/SearchProductRepositoryCustom.java
mini-project/src/main/java/com/fast/miniproject/search/repository/SearchProductRepositoryImpl.java
mini-project/src/main/java/com/fast/miniproject/search/service/SearchProductService.java

로그인 했을때 체크박스를 누르면 사용자가 구입 가능한 상품들만 보여주는 기능 구현
(로그인 여부는 프론트에서 토근 여부를 통해 확인하고 로그인 안하고 체크박스 누를시 로그인 창으로)
- Change 1
- https://github.com/FastcampusMini/mini-project/issues/72
- e2fa3745, f2f73ab8, 2705334f : 위 이슈와 관련된 Controller, Service, Repository 변경
- Change 2
- 유저 관련 Exception 생성, 스웨거 파라미터에 설명 추가

Feature/search 사용자 맞춤 검색 서비스 구현

---

mini-project/src/main/java/com/fast/miniproject/product/repository/PurchaseProductRepository.java
mini-project/src/main/java/com/fast/miniproject/product/service/impl/ProductServiceImpl.java

fix : 연봉이 Integer의 범위를 넘어설때 구매 가능 여부 체크에서 오류나는 현상 해결
